### ISSUE TITLE
dyadVarNames() function

### ISSUE THREAD

**Issue by dapgen** [jsakaluk/dySEM#1]
Hi John,

I renamed the variables of my first latent factor x1.w or x1.m and the variables of my second latent factor y1.w or y1.m

If I understand correctly, I keep both set of variables (x and y in the same dataset) and I run your first function??

When I tried to run that function: dvn.ACC <- dyadVarNames(DyadInv, xvar="x",  sep = ".",
+                         distinguish1 = "w", distinguish2 = "m")

I had this message error:

Error in dyadVarNames(DyadInv, xvar = "x", sep = ".", distinguish1 = "w",  : 
  unused argument (xvar = "x")

What does it mean that I have an unused argument? 

I tried before with the original name of my variable (concil instead of x) and I had the same error. 

And if it would have worked, would I had to run the same function, but with y like that: dyadVarNames(DyadInv, **yvar** = "y", sep = ".", distinguish1 = "w", distinguish2 = "m") ?

Thank you

**Comment by jsakaluk** [comment]
Hi Daphne, 

Answering your last question first, it depends on what you want to do. If you want to just check for dyadic invariance in either x or y, then you could create separate dvns for each. Alternatively, if you wanted to model both x and y simultaneously (for e.g., in a latent APIM), you could make use of both xvar and yvar arguments like so:

`dvn = dyadVarNames(dat, xvar="X", yvar="Y", sep = ".", distinguish1 = "1", distinguish2 = "2")`

Not sure why you are getting the error. Can you send me your data file and I'll have a look? It could be a bona fide error, or there could be something funky with how your data is being imported and/or how your variables are being named.

**Comment by dapgen** [comment]
Hi John,

My dyadic CFA model has both x and y. Here's how I have tested on MPlus
![image](https://user-images.githubusercontent.com/53063505/61650788-6fa01980-ac82-11e9-8b8f-3d1be577c2c2.png)

So if I understand correctly, even if both X and Y are in my dyadic CFA model, I can create separate dvns for each?

**Comment by jsakaluk** [comment]
Yes. See below, where I create separate dvn's for x, y, and then both x and y; I could use the first two to separately evaluate dyadic invariance in x, and then in  y, and then use the combined dvn for fitting a latent APIM or CFM or MIM.

```
dvn_x = dyadVarNames(dat1,yvar="x", sep = ".", distinguish1 = "m", distinguish2 = "w")
dvn_y = dyadVarNames(dat1, xvar="y", sep = ".", distinguish1 = "m", distinguish2 = "w")
dvn_xy = dyadVarNames(dat1, xvar="x", yvar="y", sep = ".", distinguish1 = "m", distinguish2 = "w")
```

By the way, I get no error when I go to run these on your dataset, so I'm guessing it's a data importation issue. If you want to import an SPSS .sav file, try using the foreign package's important command (and remember the specify you want it to save to a data frame). Here's the exact command I used (file.choose() will pull up a navigation window for you to find the file):

`dat1 = foreign::read.spss(file.choose(), to.data.frame = T)
`

**Comment by dapgen** [comment]
The message I get when I select the file:
 dat1 = foreign::read.spss(file.choose(), to.data.frame = T)
Error in foreign::read.spss(file.choose(), to.data.frame = T) : 
  unable to open file: 'No such file or directory'

Seems to be a bug as you say with my data importation. Do you have another code I can try or I can even prepare the data manually??

**Comment by jsakaluk** [comment]
Do you have the foreign package installed?

**Comment by dapgen** [comment]
Yes

**Comment by jsakaluk** [comment]
If you can't get foreign to play nice, I think you are going to have a very difficult time working in R with SPSS files. I would recommend exporting your data to .csv and then using the base R read.csv function.

**Comment by dapgen** [comment]
So I've logged into my university session to test if I'll get the same issue and I have an error but it's not the same: 
> dvn_x <- dyadVarNames(dat1, xvar="X",  sep = ".",
+                      distinguish1 = "1", distinguish2 = "2")
Error in loadNamespace(name) : there is no package called ‘tidyselect’

**Comment by jsakaluk** [comment]
The error message is giving you a big clue about what R's (current) hangup is :)

**Comment by dapgen** [comment]
Ok. It's now working for the dyadVarNames function. 
> dvn_x <- dyadVarNames(dat1, xvar="X",  sep = ".",
+                 distinguish1 = "1", distinguish2 = "2")
> dvn_y <- dyadVarNames(dat1, xvar="y",  sep = ".",
+                 distinguish1 = "1", distinguish2 = "2")

The error is now in the dyadCFA function:
> pconnex.config.script = dyadCFA(dvn_x, lvname = "Pconnex",  model = "configural")
Error in resids[[i]] <- sprintf("%s ~~ %s", dvn[[1]][i], dvn[[2]][i]) : 
  attempt to select less than one element in integerOneIndex

**Comment by dapgen** [comment]
Oups I just noticed an error in my code. Wait.

**Comment by dapgen** [comment]
I have the same error message : 
> dvn1 <- dyadVarNames(dat1, xvar="X",  sep = ".",
+                      distinguish1 = "1", distinguish2 = "2")
> dvn2 <- dyadVarNames(dat1, yvar="y",  sep = ".",
+                      distinguish1 = "1", distinguish2 = "2")
> con.config.script = dyadCFA(dvn1, lvname = "pconnect",  model = "configural")
Error in resids[[i]] <- sprintf("%s ~~ %s", dvn[[1]][i], dvn[[2]][i]) : 
  attempt to select less than one element in integerOneIndex

**Comment by jsakaluk** [comment]
The dyadCFA function works on your data set. The problem right now is with the dvn that you have misspecified (you've told dyadCFA to write code based on a dvn that specifies variables that do not exist in your data set). Click the resulting dvn object and you'll see for yourself.

**Comment by dapgen** [comment]
Okay I don't understand why it is misspecified, I just replaced my terms in your syntax. The dyadVarNames output says that for both dvn1 dvn2 I have 0 integer. I have checked my data and my numbers are all integer...  I don't know what it means. Is this the problem?

**Comment by dapgen** [comment]
That's fine. I just find my misspecification... didn't remember that R was case sensitive.

**Comment by jsakaluk** [comment]
Remember that the goal of dyadVarNames is to scrape the appropriate variable names for latent X/Y from your dataset. If you look at what it returns, do the variable names scraped match those that are actually in your dataset? If not, something has probably gone wrong with what you've specified for `xvar` and/or `yvar`, and/or `distinguish1` and/or `distinguish2`

**Comment by dapgen** [comment]
I'm also able to run the dyadCFA function. I'm trying to run the lavaan model-fitting function:
> con.fit.config <- cfa(con.config.script, data = dat1, std.lv = F, auto.fix.first= F, meanstructure = T)
Error in lav_data_full(data = data, group = group, cluster = cluster,  : 
  lavaan ERROR: missing observed variables in dataset: X1.1 X2.1 X3.1 X1.2 X2.2 X3.2

**Comment by jsakaluk** [comment]
Like I said: look at what is stored in your dvn. Do the variable names match what's actually in your data file? The data file you sent me does not contain any variables starting with capital "X", nor variables distinguished by "1"s and "2"s. There is a simple fix for this, but it requires you to go back and look at what you specified for your dvn and to change it.

**Comment by dapgen** [comment]
I completely forgot that my specification were w and m... sorry. Did I mention it's the first time that I use R? 👍 

Okay now I get this: > con.fit.config <- cfa(con.config.script, data = dat1, std.lv = F, auto.fix.first= F, meanstructure = T)
Error in lav_data_full(data = data, group = group, cluster = cluster,  : 
  lavaan ERROR: unordered factor(s) detected; make them numeric or ordered: x1.m x2.m x3.m x1.w x2.w x3.w

I don't understand, it is ordered.. and numeric as far as I understand.

**Comment by jsakaluk** [comment]
Hi Daphne, 
There's lots going on in this thread which is well beyond anything to do with the `dyadVarNames() `function (and these issues posts are generally intended to be fairly specific to a particular problem). Many of your spin-off questions seem to be about errors related to data importation, and how certain variables are coded and/or named. I think what's probably best is that you put a pin in this analysis for now, and invest some time in learning some basic in's and out's of R/R-Studio, otherwise I think you're in for a tough slog. As you say, this is the first time you've used R, and I think it's a potentially unreasonable expectation to hoist upon yourself that you would go from total R novice to conducting complex dyadic SEMs in R in a day! Invest a bit the the "journey" of R, and the "outcome" will follow soon enough :) 

And for what it's worth, when I view your imported data set in R, I see a number of non-numeric values for each variable (e.g., “Ne me ressemble pas du tout 1”).
