### ISSUE TITLE
Broken examples

### ISSUE THREAD

**Issue by mpadge** [jsakaluk/dySEM#41]
@jsakaluk By way of a beginning towards aligning this package with rOpenSci's new system for [peer review of statistical software](https://ropenscilabs.github.io/statistical-software-review-book/index.html). Our new [`autotest` package](https://github.com/ropenscilabs/autotest) works on this package, but fails to pick up all tests because the following examples fail:

``` r
library (dySEM)

#  from `scrapeVarLong.R`:
dvn <- scrapeVarLong(dat = dat.pkg, x_order = "sip", x_stem = "X", x_delim2=".", x_item_num="\\d+", distinguish_1="1", distinguish_2="2",
y_order="sip", y_stem="Y", y_delim2=".", y_item_num="\\d+")
#> Error in scrapeVarLong(dat = dat.pkg, x_order = "sip", x_stem = "X", x_delim2 = ".",  : 
#>  object 'x1vars' not found

# from `scriptBifactor`:
dvn = dyadVarNames(dat, xvar="X", sep = ".",distinguish1 = "1", distinguish2 = "2")
#> Error in dyadVarNames(dat, xvar = "X", sep = ".", distinguish1 = "1",  : 
#>  could not find function "dyadVarNames"

# from `scriptCFM` also does not work:
dvn <- scrapeVarCross(dat = DRES, x_order = "sip", x_stem = "PRQC", x_delim1 = "_", x_delim2=".", x_item_num="\\d+", distinguish_1="1", distinguish_2="2",
y_order="sip", y_stem="sexsat", y_delim2=".", y_item_num="\\d+") # that's okay, but ...
fm.script.config = scriptCFM(dvn, lvxname = "Quality",
                             lvyname = "SexSat", model = "configural", scaleset = "MV")
#> Error in scriptCFM(dvn, lvxname = "Quality", lvyname = "SexSat", model = "configural",  : 
#>  unused argument (scaleset = "MV")
```

The [`autotest` package](https://github.com/ropenscilabs/autotest) works by scraping examples and changing the inputs demonstrated there, but it requires the examples to actually run to be able to identify those inputs. Results thus far are nevertheless very encouraging: excepting these three functions which can't be tested, a total of 57 tests generate only 4 notes, 3 of which are about examples not demonstrating usage of parameters (`y_delim1@scrapeVarCross`, `lvyname@scriptINULL`, and `lvyname@scriptISAT`).

**Comment by jsakaluk** [comment]
@mpadge thanks for this, and this is indeed very encouraging (and frankly, given its my first sincere rodeo with pkg dev, a bit [pleasantly] surprising)! 

The good news is that these errors should be resolved soon. Your advice to determine and hone in on the "core functionality" of the package has been very helpful, and I've been spending the last week taking a careful look at the functions I had in the package:  expunged those that were forgotten relics and/or not yet ready for primetime, and focusing on improving the organization and documentation of those remaining. 2/3 of these issues are actually ones I had already identified as needing a fix before the first "stable release" (i.e., when I share dySEM's existence with dyadic data analysis users at the SPSP Close Relationships Preconference, on Feb. 9), and I am also currently--and will continue to--working my way through the examples to make sure all are running smoothly, and will have a look at those specific ones you mention. 

Shall I update you (and if so, is the appropriate procedure to tag you?) once these issues--and others (I can see it doesn't look to difficult to use/interpret autotest myself--are squared away? 

Thanks again for this opportunity and this feedback--it's a very exciting development!

**Comment by mpadge** [comment]
Update: I had inadvertently neglected one `!` in the code, which caused lots of tests to be dropped. There are actually 179 tests which would be run, but can't be until #43 is fixed. You can run `autotest(..., test = FALSE)` for yourself to see them, but I do not recommend running `autotest(..., test = TRUE)` :smirk:
