### ISSUE TITLE
Use element name instead of number for extracting information from `dvn`

### ISSUE THREAD

**Issue by omarjcamanto** [jsakaluk/dySEM#94]
- [ ] esHelpers.R
- [ ] getDyReliability.R
- [ ] outParamHelpers.R
- [ ] scriptAPIM.R
- [ ] scriptBiDy.R
- [ ] scriptCFA.R
- [ ] scriptCFM.R
- [ ] scriptMIM.R

**Comment by jsakaluk** [comment]
@omarjcamanto is this squared away completely?
